apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "foundry-vtt.fullname" . }}
  labels:
    {{- include "foundry-vtt.labels" . | nindent 4 }}
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      {{- include "foundry-vtt.selectorLabels" . | nindent 6 }}
  template:
    metadata:  
      labels:
        {{- include "foundry-vtt.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "foundry-vtt.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: volume-mount-permission
          image: busybox
          command: ["sh", "-c", "chown -R 421:421 /data "] 
          volumeMounts:
          - name: data
            mountPath: /data
          resources:
            limits:
              cpu: 128m
              memory: 128Mi
      containers:
      - name: {{ .Chart.Name }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - name: http
            containerPort: 30000
            protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: http
        readinessProbe:
          httpGet:
            path: /
            port: http
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        env:
          - name: FOUNDRY_ADMIN_KEY
            value: {{ (default "admin" .Values.foundryvtt.adminKey) | quote }}
          {{- if .Values.foundryvtt.upnp }}
          - name: FOUNDRY_UPNP
            value: {{ .Values.foundryvtt.upnp }}
          {{- end }}
          {{ if .Values.foundryvtt.hostname }}
          - name: FOUNDRY_HOSTNAME
            value: {{ .Values.foundryvtt.hostname }}
          {{ end }}
          {{ if .Values.foundryvtt.noUpdate }}
          - name: FOUNDRY_NO_UPDATE
            value: {{ .Values.foundryvtt.noUpdate | quote}}
          {{ end }}
          {{ if .Values.foundryvtt.routePrefix }}
          - name: FOUNDRY_ROUTE_PREFIX
            value: {{ .Values.foundryvtt.routePrefix }}
          {{ end }}
          {{ if .Values.foundryvtt.sslCert }}
          - name: FOUNDRY_SSL_CERTâˆ‚
            value: {{ .Values.foundryvtt.sslCert }}
          {{ end }}
          {{ if .Values.foundryvtt.sslKey }}
          - name: FOUNDRY_SSL_KEY
            value: {{ .Values.foundryvtt.sslKey }}
          {{ end }}
          {{ if .Values.foundryvtt.proxyPort }}
          - name: FOUNDRY_PROXY_PORT
            value: {{ .Values.foundryvtt.proxyPort | quote }}
          {{ end }}
          {{ if .Values.foundryvtt.proxySSL }}
          - name: FOUNDRY_PROXY_SSL
            value: {{ .Values.foundryvtt.proxySSL | quote }}
          {{ end }}
          {{- if eq .Values.foundryvtt.s3.awsConfig "true" -}}
          - name: FOUNDRY_AWS_CONFIG
            value: "true"
          {{- else if eq .Values.foundryvtt.s3.awsConfig "file" -}}
          - name: FOUNDRY_AWS_CONFIG
            value: "/etc/secretaws/aws-credentials.json"
          {{- end }}
          {{ if .Values.foundryvtt.updateChannel }}
          - name: FOUNDRY_UPDATE_CHANNEL
            value: {{ .Values.foundryvtt.updateChannel }}
          {{ end }}
          {{ if .Values.foundryvtt.world }}
          - name: FOUNDRY_WORLD
            value: {{ .Values.foundryvtt.world | quote }}
          {{ end }}
        volumeMounts:
        - name: data
          mountPath: /data
      {{- if eq .Values.foundryvtt.s3.awsConfig "file" }}
        - name: secret-aws
          mountPath: "/etc/secretaws/"
          readOnly: true
      {{- end }}
      {{- if .Values.letsEncrypt.enabled }}
        - name: tls
          mountPath: "/etc/ssl/foundryvtt"
          readOnly: true
      {{- end }}       
    {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
    {{- if eq .Values.foundryvtt.s3.awsConfig "file" }}
      - name: secret-aws
        secret:
          secretName: {{ include "foundry-vtt.fullname" . }}-aws
    {{- end }}
    {{- if .Values.letsEncrypt.enabled }}
      - name: tls
        secret:
          secretName: {{ include "foundry-vtt.fullname" . }}-tls
    {{- end }}
      - name: data
    {{- if .Values.persistence.dataDir.enabled }}
        persistentVolumeClaim:
          claimName: {{ template "foundry-vtt.fullname" . }}
    {{- else }}
        emptyDir: {}
    {{- end }}
